### ISSUE TITLE
Not an issue, only an idea ;-)

### ISSUE THREAD

**Issue by Florandoa** [shudnal/ProtectiveWards#1]
Could you add configurable repair (%), after certain time (in sec or minutes), and a reduced stamina/food drain (%) ? Thank you, have a nice weekend. :-)

**Comment by shudnal** [comment]
Both of your ideas already implemented at BetterWards by Azumatt. 
https://valheim.thunderstore.io/package/Azumatt/BetterWards/
I don't want to duplicate the functionality besides "Protective" and basic ones :). 
Although reduces stamina drain isn't implemented it's better be included in BetterWards than this mod so you better send the idea to Azumatt.

**Comment by shudnal** [comment]
I have checked your another opened issue and consider to think about a little extension to functionality since BetterWards is indeed already bloated and we need something more lightweight.

**Comment by shudnal** [comment]
@Florandoa I've made new 1.1.0 release for Hildir patch. I won't publish it until public stable Hildir release. But you can take it from release section here.
