### ISSUE TITLE
Boss Trophy Offering - ArgumentException: An item with the same key has already been added

### ISSUE THREAD

**Issue by Moj-FPS** [shudnal/ProtectiveWards#3]
Hey man, sorry to bother you again but I'm running into a similar error (as the one that was just patched) when offering a trophy to the ward to taxi to the Sacrificial Stones. When offering an Eikthyr trophy (haven't got around to testing with other boss trophies yet), I receive this error in the log:

```
[Error  : Unity Log] ArgumentException: An item with the same key has already been added. Key: (-5.56, 50.69, 4.66)
Stack trace:
System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) (at <17d9ce77f27a4bd2afb5ba32c9bea976>:0)
System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) (at <17d9ce77f27a4bd2afb5ba32c9bea976>:0)
ZoneSystem.GetLocationIcons (System.Collections.Generic.Dictionary`2[TKey,TValue] icons) (at <1f17a254067e41d0b59746dec98ad607>:0)
ProtectiveWards.WardOfferings.TryGetFoundLocation (System.String name, UnityEngine.Vector3 position, UnityEngine.Vector3& target) (at <7b3f960d5d4447ab94011b50037f3eaf>:0)
ProtectiveWards.WardOfferings.TaxiToLocation (ItemDrop+ItemData item, Player initiator) (at <7b3f960d5d4447ab94011b50037f3eaf>:0)
ProtectiveWards.WardOfferings+PrivateArea_UseItem_Offerings.Postfix (PrivateArea __instance, Humanoid user, ItemDrop+ItemData item, System.Boolean& __result) (at <7b3f960d5d4447ab94011b50037f3eaf>:0)
(wrapper dynamic-method) PrivateArea.DMD<PrivateArea::UseItem>(PrivateArea,Humanoid,ItemDrop/ItemData)
(wrapper dynamic-method) Humanoid.DMD<Humanoid::UseItem>(Humanoid,Inventory,ItemDrop/ItemData,bool)
Player.UseHotbarItem (System.Int32 index) (at <1f17a254067e41d0b59746dec98ad607>:0)
(wrapper dynamic-method) Player.DMD<Player::Update>(Player)
```

I have made sure all requirements were met (teleportable, unencumbered, over 300m away, etc.). I have attached a few screenshots just in case they are useful. 

Thank you again!

![protwards1](https://github.com/user-attachments/assets/fd9e16ac-b829-4567-a6f7-0f8407d96637)
![protwards2](https://github.com/user-attachments/assets/38af3c8d-300d-4d1b-a696-fd2d23bbbef1)
![protwards3](https://github.com/user-attachments/assets/02e54cb3-7f13-4fe2-a953-a2f6543f8728)

**Comment by shudnal** [comment]
Thanks. 1.2.2 is available at https://thunderstore.io/c/valheim/p/shudnal/ProtectiveWards/versions/

**Comment by Moj-FPS** [comment]
You are by far the most responsive mod author I've ever seen. Appreciate it a lot! Thanks again!

**Comment by shudnal** [comment]
Well it was a matter of minute to fix and another minute to upload a new version. Thanks to you for reporting.
