### ISSUE TITLE
Not syncing from server to client.

### ISSUE THREAD

**Issue by rmcendre** [shudnal/ProtectiveWards#4]
When adding the protectivewards mod to the server, it is not syncing the config with the clients. IE they change their config and it still works.
For example, I have the server cfg file set to auto close doors after 10 secs, but if I change the config on my client computer, it will use whats is on the client machine, not what is set on the server.

**Comment by shudnal** [comment]
Do you have General ->Lock Configuration set to true? In other case any client will be able to change config values.
Are your client is in admin list on the server? In that case you will be able to change config values.
Are you sure you have no error in log file both client and server one? There could be errors that prevent config values from sync.
